### ISSUE TITLE
Create Probes Form

### ISSUE THREAD

**Issue by nicnocquee** [hyperjumptech/monika-config-generator#8]
![Probes](https://user-images.githubusercontent.com/311343/112959094-5f248f80-9143-11eb-8876-d9826dc85975.png)

**Comment by dennypradipta** [comment]
What does this button do?
![image](https://user-images.githubusercontent.com/16670475/113532732-4827e680-95f6-11eb-9e59-8a5d853355c4.png)

**Comment by nicnocquee** [comment]
> What does this button do?
> ![image](https://user-images.githubusercontent.com/16670475/113532732-4827e680-95f6-11eb-9e59-8a5d853355c4.png)

Show popup menu with item: Delete probe
